api:
  dashboard: true
  insecure: false   # mets true si tu veux accéder au dashboard sans https, sinon laisse à false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

tls:
  certificates:
    certFile: "/etc/traefik/certs/cert.crt"
    keyFile: "/etc/traefik/certs/cert.key"